from ..extensions import db


class Folhasbmf(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    numero_da_corretora = db.Column(db.String(40))
    nr_nota = db.Column(db.String(40))
    folha = db.Column(db.String(40))
    data_pregao = db.Column(db.String(40))
    cnpj_cpf = db.Column(db.String(40))
    código_cliente = db.Column(db.String(40))
    venda_disponível = db.Column(db.String(40))
    compra_disponível = db.Column(db.String(40))
    venda_opções = db.Column(db.String(40))
    compra_opções = db.Column(db.String(40))
    valor_dos_negócios = db.Column(db.String(40))
    irrf = db.Column(db.String(40))
    irrf_day_trade_proj = db.Column(db.String(40))
    taxa_operacional = db.Column(db.String(40))
    taxas_bmf = db.Column(db.String(40))
    taxa_registro_bmf = db.Column(db.String(40))
    outros_custos = db.Column(db.String(40))
    impostos = db.Column(db.String(40))
    ajuste_posição = db.Column(db.String(40))
    ajuste_day_trade = db.Column(db.String(40))
    total_das_despesas = db.Column(db.String(40))
    outros = db.Column(db.String(40))
    irrf_operacional = db.Column(db.String(40))
    total_conta_investimento = db.Column(db.String(40))
    total_conta_normal = db.Column(db.String(40))
    total_liquido = db.Column(db.String(40))
    total_liquido_da_nota = db.Column(db.String(40))


class Operaçõesbmf(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    numero_da_corretora = db.Column(db.String(40))
    nr_nota = db.Column(db.String(40))
    folha = db.Column(db.String(40))
    data_pregao = db.Column(db.String(40))
    cnpj_cpf = db.Column(db.String(40))
    código_cliente = db.Column(db.String(40))
    cv = db.Column(db.String(40))
    mercadoria = db.Column(db.String(40))
    vencimento = db.Column(db.String(40))
    quantidade = db.Column(db.String(40))
    preçoaajuste = db.Column(db.String(40))
    tiponegócio = db.Column(db.String(20), default=0)
    vlrdeoperação = db.Column(db.String(40))
    dc = db.Column(db.String(40))
    taxaoperacional = db.Column(db.String(40))
