from ..extensions import db


class Folhasb3(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    numero_da_corretora = db.Column(db.String(40))
    nr_nota = db.Column(db.String(40))
    folha = db.Column(db.String(40))
    data_pregao = db.Column(db.String(40))
    cnpj_cpf = db.Column(db.String(40))
    código_cliente = db.Column(db.String(40))
    debêntures = db.Column(db.String(40))
    vendas_à_vista = db.Column(db.String(40))
    compras_à_vista = db.Column(db.String(40))
    compra_opções = db.Column(db.String(40))
    venda_opções = db.Column(db.String(40))
    operações_termo = db.Column(db.String(40))
    valor_das_oper_títulos_públ = db.Column(db.String(40))
    valor_das_operações = db.Column(db.String(40))
    valor_líquido_das_operações = db.Column(db.String(40))
    taxa_de_liquidação = db.Column(db.String(40))
    taxa_de_registro = db.Column(db.String(40))
    total_clbc = db.Column(db.String(40))
    taxa_de_termoopções = db.Column(db.String(40))
    taxa_ana = db.Column(db.String(40))
    emolumentos = db.Column(db.String(40))
    total_bovespa = db.Column(db.String(40))
    taxa_operacional = db.Column(db.String(40))
    execução = db.Column(db.String(40))
    taxa_de_custódia = db.Column(db.String(40))
    impostos = db.Column(db.String(40))
    irrf = db.Column(db.String(40))
    outros = db.Column(db.String(40))
    total_custos_despesas = db.Column(db.String(40))
    liquido = db.Column(db.String(40))


class Operaçõesb3(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    numero_da_corretora = db.Column(db.String(40))
    nr_nota = db.Column(db.String(40))
    folha = db.Column(db.String(40))
    data_pregao = db.Column(db.String(40))
    cnpj_cpf = db.Column(db.String(40))
    código_cliente = db.Column(db.String(40))
    q = db.Column(db.String(40))
    negociação = db.Column(db.String(40))
    cv = db.Column(db.String(40))
    tipo_mercado = db.Column(db.String(40))
    prazo = db.Column(db.String(40))
    especificação_do_título = db.Column(db.String(40))
    obs = db.Column(db.String(40))
    quantidade = db.Column(db.String(40))
    preçoajuste = db.Column(db.String(40))
    vlrdeoperação = db.Column(db.String(40))
    dc = db.Column(db.String(40))
